on: 
  push

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 checks
        run: flake8 src/app_test.py

  Flake8Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flake8
        run:  pip install flake8
        
      - name : Check code with Flake8
        run: flake8 ./src/app_test.py

  Editor-Conf-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Editor-Conf-Checker
        run: pip install editorconfig-checker

      - name: Editor-Conf Check
        run: ec -version

  MarkdownFilesCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Markdown File Link Check
        uses: ruzickap/action-my-markdown-link-checker@v1.1.2


  UnitTest:
    runs-on: ubuntu-latest
    needs: [Flake8Test, Editor-Conf-Check, MarkdownFilesCheck]
    steps:
     - name: Prepare repo
       uses: actions/checkout@master
       
     - name : Set up Python
       uses: actions/setup-python@v1
       
     - name: install requirements
       run: pip3 install -r src/requirements.txt
       
     - name: Test
       run: python3 -m unittest ./src/app_test.py
  
